# This is a simple GitHub Actions workflow to make sure you have the commits on master to merge the PR
# Added comment to add to branch pr rules
name: Basic Check

on:
  pull_request:
    branches: [ master ]

jobs:
  status-check:
    runs-on: ubuntu-latest
    steps:
    - name: Simple check
      run: echo "Check passed" && exit 0